// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Enrich telemetry attributes with compliance control data
	// (POST /v1/enrich)
	PostV1Enrich(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostV1Enrich operation middleware
func (siw *ServerInterfaceWrapper) PostV1Enrich(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1Enrich(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/v1/enrich", wrapper.PostV1Enrich)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RYXXPbuhH9KztoZ9rOULKc9Gv05qskcz3Te61avn2J/QCBKwkxCDDAUo6a8X/vLAiK",
	"H6LsZNL7JhFY4Ozu2d1DfhXKFaWzaCmI+VcR1A4LGX8uXFEaLa1C/ifzXJN2VpqldyV60hjEfCNNwEzk",
	"GJTXJa+LeccQciSpTYCNdwXcLFYfYIWq8poOsHCWvDOw9G6jDU5FJsrOyQwsbuCff/S4EXPxh4sW7EVC",
	"etHelk4Uz5lA67XaFWhpRZKqeF4fZP0c3AZoh6BayK0plN4pDGEOq0rxjwx+s4UsS8wzWEpPWhp+9Gjd",
	"k83AeVg9al5lX9BWhZh/FMlUZKKxFZlIxvFhtBaZSLbiIRP4RRalQUZ5tKZDyQ8CeW237OLGywKfnH8M",
	"3x6hD63Ncya8Do/fbnvLu5/ZDD9X2mPO3jU56sEZCf9DJkhTdKlDq6NXbv0JFTGm02yeZq5hULoctN04",
	"X0heho3z3WTKEDAEBnJCL1mWRiu51kbT4fSW93avvbNsGiAeagm/UICnHXoE2ulwBBCPwuh4k7mPYuld",
	"Xql4WsZs23LeHjKhCYsI4CSj6YH0Xh74v5Ikjdte56fofrP6c4Wgc7SkNxp9dJyZHIbRSaewD8ccdZGK",
	"m9VyNflpjGJKEm6dH4nOIq3EU2WhzQFoJ2kcwRqNs9sA5Hr3XkVqN31g7H79Y56vUdttokAsu4HP/76a",
	"zP4xnV2OXe2xwFxHTr3r3j+E01lseolH5YoCbY45dI6BQJ6jdkiAW/70kN1i4fYI3jmCKqAHWYdJ2hw0",
	"72k6U4kerq9+gdIZrWr2DbwY1KrmELSc6qT34cVC/NBrNGdb/ZFcEWq6OILt1OdJFW5eOPwWt5WRlGim",
	"bV4F8gcIJG0ufR5SgnEvTSUJ80Hx98vx1+vV3eSfs9nkb2+5Hm8WkzffV40dj14ORM/1I03TDGSCtD4P",
	"PehDvlpMmJuLxd+nl9+DdZD3XmfuefFy3m/TeDjvqA6PnQ77Yp4N7nGkl/MdENf4IKd0zOOTph1YZyf9",
	"ZKaJuvCatIrT82e93YlM/IK5rgqRiX+5J5GJ6xaHNP15mgxeLpQa61hw3h/n2i1+rjDQGGnjApTyYJys",
	"OUnIZcvclUReryvqyoyTWMWKPrw2mZf1riH4ZPwa+lA6G/BMepF6iqhAkrkkCdoqU+XM2KbFsqLRdhuy",
	"DqmzITGmXVrXgrPVlR2VN5jI50doZzC206sdVqeTRecjPf9ci/+BFjyqPDsirt/tuv/ONqh+2xk2hY6K",
	"SxVWU/yZaTGU092wf5vmG9F7x6VRhnnvfKTw4Op8hGo/390tuZmzDI87Oiz562yWibqKxVxoS2/ftGWr",
	"LeEWPV9YYAhyO3J4RALN8msVn65vto+5tjwW5ZmCwT03e4XAYiv2+roUAe1WW6zpMypNgZwz4UwbeB+t",
	"f5XFiJP8tFEdvctqMVai5xBiHjekIROFigfkHqlqJsumxDr6aHk1porqS24rg98nShM4Xxk8GdotmL5E",
	"y9EeJlyDE67BV1N4Eq0B2tOc8gk8sk4duQKFlrw0+r+Yj3bCgH6PPoXZO059SF5OyE26Jk2HvLdN0+y2",
	"yqiV+u0yxLClw2SYMDmBt2+MewpTuGPpyAC0whpIABng3nKkZUU75zVJ0nuE4CrP0qz/UtR4kQFauTac",
	"jpsS7d1xSilnDCpyviatox16uLfhEFiBALk0vY6ka6mF++hBnOCNUBtGMb1KZXBvfSvx2lFyjIkyMgS9",
	"0SqeHab3TNLue6QMAVYpElfLa5GJPfpQJ3E2vZzOmLSuRCtLLebi7XQ25eZaStrFErvYX17UrtQFNzbQ",
	"eZiUFICTTlxtj3gYm+gB/ozT7TSLmSS4fpc14bGywKyeJNfv/sLuseNUeRug/azSidDEo4m10Tl8LQMX",
	"iwXufp73566Q2nK70Wp6byMt0Oal06zFQtwYX0LIwRpBSWMwh/UBpB3ke9Hk+08BVBWIe1f96cP5Oujc",
	"l2IS4sxdukD/uazlRNKUGOgnlx+aic6ypp3obHjxKdTvT/WUeW0GnSqt537Fk68wPqiVTEznm9nsdwGQ",
	"xFJEMPgWUY/2TWXMIRVFL20iWmxkZej/hywO2REwlcUvJSomDqY9mQhVUcioimqPxqkb63VQotyquE3w",
	"Vc//CwAA//99oJXYKBQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
