// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Enrich telemetry attributes with compliance control data
	// (POST /v1/enrich)
	PostV1Enrich(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostV1Enrich operation middleware
func (siw *ServerInterfaceWrapper) PostV1Enrich(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1Enrich(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/v1/enrich", wrapper.PostV1Enrich)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RYW2/juBX+KwRboC0gO0pmty38ls1ksC66iRtn+9BNHhjx2OaGIjUkZY8xyH8vDklJ",
	"1MVJBtO+2ebl3L7znY/+SgtdVlqBcpYuvlJb7KBk/uOVLispmCoAvzHOhRNaMbkyugLjBFi62DBpIaMc",
	"bGFEhet0kRwkHBwT0pKN0SW5vVp/ImsoaiPckVxp5YyWZGX0RkiY04xWyc3omN+AH/9oYEMX9A9nnbNn",
	"0dOzzlq8kb5kFJQRxa4E5daOudrf13cy/E70hrgdkKJzuTtKKqMLsHZB1nWBHzLyqypZVQHPyIoZJ5jE",
	"n56VPqiMaEPWzwJXMRZQdUkXv9F4lGa0OUszGg/7H/1pmtF4lj5mFL6wspKAXran3bHCH6wzQm0xxI1h",
	"JRy0ebbvz9Cn7sxLRo2wz+8/e4e7XzJqTyQ0qXrc0iWhWXM0ozdazdLv11+grMKCI5dVJUXBniQkuell",
	"ZHh8kBcMCz7XwgBHww2GeulqY5jAyWNGnXDeUoL/1ox++h0Kh2kYw24MsQbq0Qsi1EabkuEy2WiToo5Z",
	"C9aiI6M+YDEnQgp3HFu5VnthtMKjlvhLlYMvzpLDDgwQtxO2dcBfBT7wJqG/0ZXRvC78bRm2xRYT+ZhR",
	"4aD0DoygF39gxrAjfi+YY1Jvl3zs3a9KfK6BCA7KiY0A4wPHlrPD7MRbMIa2WKmn9Ha9Ws9+muqFgjnY",
	"ajORnau44m9lpZBH4nbMTXvwBFKrrSVO9+xe+h5sCGvKvvi+yJ9AqG2EgOeHQcz/upzlf5vn51OmDZTA",
	"hcfUx9T+0J1ksSE9A4UuS1AcOEmuIdYZzNoxOtzhp+fZHZR6D8Ro7UhtwRAW0sQUJwL3NBRagSHLy19I",
	"paUoAvpeb1qBKegwlZT38dVG/NRjxJPs1ILLuxoNe2eT/hx14eaVy+9gW0vmIsyE4rV15og0qDgz3MYC",
	"w57Jmjngg+bvt+PNcn0/+3uez378gP14ezW7+LZuTCJ6PRG90FuYxmGNAOliHkbQd/nyaobYvLr66/z8",
	"W3wd1L1H0b0oXq/7XZxjpwMV9jlh2FfrLGEPE1yONohfw4t0IXwdD8LtiNJq1i9mM/WMcKLwY/5nsd3R",
	"jP4CXNQlzeg/9YFmdNn5wWR/zMUD40YZ5eG6HWF38LkG66bw6RdIxY5SswA/B9ihCFPmnBFPtUulT1rf",
	"rxT2CI+gA30XH6/VVii4YaXnqNUlpjEsBIQIrRrhRT8xIT1iwo67WgJOCspBHWdIHzOkDyw5O3xkjqEV",
	"A8wG14f0IixR2hEmpT74Ww3YWrp4n8eYKME6VlZ0QS/yix9m+fns/Mf783zxIV/k+X98GvtFTwN8TQ1d",
	"N/uG0G0veHyjQrbSysLUFMc9wFNNsBGKY9d5lAUMN6UKNOt2BpgjKCuF2tp5v2pFT78nanogKE4rgGSu",
	"d8O3m7XjwSj4xMg6NaG+Y4JMKvxELPfJOv12kl/7rDnktEQtR4IIHZro4YEyHYOsX4/3ie4JQdsuTULN",
	"GG18mw5M8wnM/Xx/v4panfgdCXx+yPOMBnaiCyqU+3DR0ZFQDrZg0GAJ1rLtFKDRE9Isv63Tvflm+2Ro",
	"SY9OMD0gf8UtBGWkn2KBcgh4ugrImhTdxGkt7WgYjMluaBt/bfRUz1iQmRUYTCJwvwFackSdAMj+RQA5",
	"a7ovUX6eVUcT9BTNjjkfaXHoWnssGVP47rqrlX+WRv3ZUvYNALfkDvYCDu9+orWnTzjfTID3K+bovqkl",
	"jLRUl8m+ch6Nl7F07ubNIHfsQP6xvr0hunZV7TpB1Ktwn21LcIzH296cQBndg7HB2Pk8D6rtOybesFcS",
	"B4ax3e+A4DI+D1V4BrBD1zkHZskWFJihyjsVSMsRnDmY4c1vNnvnXTbusAFITgJ+TBFoBpXdOObL1bKF",
	"EpIFs5ZYMHtRwJzc4wMnfsNhg5loXzyzJ2aBT0qkgYrC2mcPCqeD8QOUIEsaxSThumRCISmJIs7tzo/K",
	"aHT/TzYlJmwqCXwL8we1xDUOVmwV0ogmT0AKJiVw8nQkTJHbCtR968eVlhIKpw3eWFuHJBj+xkJ3dQwA",
	"nbEZwSOisFnwyrAC7PwBmSD9DwS9XMf8XK6WPfDm8whfXYFilaAL+mGez3GyVsztPC+d7c/PgtVAqVMK",
	"FZVE5SxhxIInrWc4TklUS/4M8+0889TtyPJj1vSkYiVkoW+WH/+CAT0oA642ypLuv8skyTMD0hNIcnmo",
	"tlbTtZs/KA8WULzSAt8R1m/0D+jvKkxIOk4eD3EvuFbaun+fB10Y30Ng3U+aHxs5hzq9k3N48Ox3G97+",
	"QUm8KWdHT4eXfq86U4P/IchWX86LPP+/OBCVsfdg8D9a0HWbWspjxG+vbNSf2DBPiv8rz7yQmnCmVvCl",
	"ggKBA3FPRm1dlsxL4hDRNHS9jk+6vPn7x4+Nl5eXl/8GAAD//7oavvaNFwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
